apiVersion: v1
kind: Secret
metadata:
  name: sentiments-stack-secrets
type: Opaque
stringData:
  minio_user: {{ .Values.minio.user }}
  minio_password: {{ .Values.minio.password }}
  postgres_user: {{ .Values.postgresql.auth.user }}
  postgres_password: {{ .Values.postgresql.auth.password }}
  postgres_db: {{ .Values.postgresql.auth.database }}
