apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiments-front-config
data:
  STREAMLIT_API_URL: http://sentiments-api-service:8000
---
# ---------------------------
# Streamlit Frontend Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiments-front-deployment
spec:
  replicas: {{ .Values.streamlit.replicas | default 1 }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: "{{ .Values.streamlit.image }}"
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: sentiments-front-config
      imagePullSecrets:
        - name: dockerhub-secret
---
# ---------------------------
# Streamlit Frontend Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: sentiments-front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
