{{- if and .Values.ingress.enabled .Values.api.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-underscores-in-headers: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentiments-api-service
                port:
                  number: 8000
{{- end }}

{{- if and .Values.ingress.enabled .Values.streamlit.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.streamlit.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentiments-front-service
                port:
                  number: 8501
{{- end }}
