name: Deploy Sentiment Services - CI

on:
  workflow_call:
    inputs:
      service:
        default: "Le service à deployer"
        required: true
        type: string
      release_name:
        default: "Le nom du release"
        required: true
        type: string
      sha:
        description: "Le SHA du commit"
        required: true
        type: string
      env_block:
        description: "les variables du values du chart helm encodé en base64"
        required: true
        type: string

jobs:
  deploy:
    name: "${{ inputs.service }} with Helm !"
    runs-on: ubuntu-latest
    environment: hetzner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Decode and export variables
        run: |
          echo "${{ inputs.env_block }}" | base64 -d > .envvars
          cat .envvars
          grep '^export ' .envvars | sed 's/^export //' >> $GITHUB_ENV

      - name: Override helm chart values
        run: |
          envsubst < deployments/${{ inputs.service }}/values.yaml > override_values.yaml
          cat override_values.yaml

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy ${{ inputs.service }} via Helm
        run: |
          helm upgrade --install ${{ inputs.release_name }} ./deployments/${{ inputs.service }} -f override_values.yaml